# Generated by Django 3.2.9 on 2021-11-25 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dep', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('head', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('num_of_vac_days', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_data', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('salary', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=7)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.department')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.positions')),
            ],
        ),
        migrations.CreateModel(
            name='VacHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('num_of_days', models.PositiveIntegerField(default=10)),
                ('that_time_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.positions')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.worker')),
            ],
        ),
        migrations.CreateModel(
            name='PosHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.worker')),
                ('worker_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.positions')),
            ],
        ),
    ]
