# Generated by Django 3.2.9 on 2021-11-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20211128_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='salary',
            new_name='pos_salary',
        ),
    ]
