# Generated by Django 3.2.9 on 2021-11-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_rename_salary_positions_pos_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='pos_salary',
            new_name='salary',
        ),
    ]
